# Generated by Django 3.0.6 on 2020-05-31 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCommet',
            new_name='SubComment',
        ),
    ]
