# Generated by Django 3.0.6 on 2020-06-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20200607_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcomment',
            name='name',
            field=models.CharField(default='k', max_length=200),
            preserve_default=False,
        ),
    ]
